version: "3.9"

services:
  ecosort:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      # Permet de mettre à jour le modèle entraîné (.ckpt) sans reconstruire l'image
      - ../Model_Dl/models/weights:/app/Model_Dl/models/weights
