version: "3.9"
services:
  ecosort:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      # Permet de mettre à jour le modèle entraîné sans reconstruire l'image
      - ../model_DL/models/weights:/app/model_DL/models/weights